<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MMCitiesSeeder extends Seeder
{
    public function run()
    {
        DB::beginTransaction();
        DB::unprepared("
INSERT INTO `cities` VALUES ('Danubyu', 'AYR', null);
INSERT INTO `cities` VALUES ('Dedaye', 'AYR', null);
INSERT INTO `cities` VALUES ('Einme', 'AYR', null);
INSERT INTO `cities` VALUES ('Hinthada', 'AYR', null);
INSERT INTO `cities` VALUES ('Ingapu', 'AYR', null);
INSERT INTO `cities` VALUES ('Kangyidaunt', 'AYR', null);
INSERT INTO `cities` VALUES ('Kyaiklat', 'AYR', null);
INSERT INTO `cities` VALUES ('Kyangin', 'AYR', null);
INSERT INTO `cities` VALUES ('Kyaunggon', 'AYR', null);
INSERT INTO `cities` VALUES ('Kyonpyaw', 'AYR', null);
INSERT INTO `cities` VALUES ('Labutta', 'AYR', null);
INSERT INTO `cities` VALUES ('Lemyethna', 'AYR', null);
INSERT INTO `cities` VALUES ('Maubin', 'AYR', null);
INSERT INTO `cities` VALUES ('Mawlamyinegyun', 'AYR', null);
INSERT INTO `cities` VALUES ('Myanaung', 'AYR', null);
INSERT INTO `cities` VALUES ('Myaungmya', 'AYR', null);
INSERT INTO `cities` VALUES ('Ngapudaw', 'AYR', null);
INSERT INTO `cities` VALUES ('Nyaungdon', 'AYR', null);
INSERT INTO `cities` VALUES ('Pantanaw', 'AYR', null);
INSERT INTO `cities` VALUES ('Pathein', 'AYR', null);
INSERT INTO `cities` VALUES ('Pyapon', 'AYR', null);
INSERT INTO `cities` VALUES ('Thabaung', 'AYR', null);
INSERT INTO `cities` VALUES ('Wakema', 'AYR', null);
INSERT INTO `cities` VALUES ('Yegyi', 'AYR', null);
INSERT INTO `cities` VALUES ('Zalun', 'AYR', null);

INSERT INTO `cities` VALUES ('Bago', 'BGO', null);
INSERT INTO `cities` VALUES ('Daik-U', 'BGO', null);
INSERT INTO `cities` VALUES ('Kawa', 'BGO', null);
INSERT INTO `cities` VALUES ('Kyaukkyi', 'BGO', null);
INSERT INTO `cities` VALUES ('Kyauktaga', 'BGO', null);
INSERT INTO `cities` VALUES ('Nyaunglebin', 'BGO', null);
INSERT INTO `cities` VALUES ('Oktwin', 'BGO', null);
INSERT INTO `cities` VALUES ('Phyu', 'BGO', null);
INSERT INTO `cities` VALUES ('Shwegyin', 'BGO', null);
INSERT INTO `cities` VALUES ('Tantabin', 'BGO', null);
INSERT INTO `cities` VALUES ('Taungoo', 'BGO', null);
INSERT INTO `cities` VALUES ('Thanatpin', 'BGO', null);
INSERT INTO `cities` VALUES ('Waw', 'BGO', null);
INSERT INTO `cities` VALUES ('Yedashe', 'BGO', null);
INSERT INTO `cities` VALUES ('Gyobingauk', 'BGO', null);
INSERT INTO `cities` VALUES ('Letpadan', 'BGO', null);
INSERT INTO `cities` VALUES ('Minhla', 'BGO', null);
INSERT INTO `cities` VALUES ('Monyo', 'BGO', null);
INSERT INTO `cities` VALUES ('Nattalin', 'BGO', null);
INSERT INTO `cities` VALUES ('Okpho', 'BGO', null);
INSERT INTO `cities` VALUES ('Padaung', 'BGO', null);
INSERT INTO `cities` VALUES ('Pauk Kaung', 'BGO', null);
INSERT INTO `cities` VALUES ('Paungde', 'BGO', null);
INSERT INTO `cities` VALUES ('Pyay', 'BGO', null);
INSERT INTO `cities` VALUES ('Shwedaung', 'BGO', null);
INSERT INTO `cities` VALUES ('Thayarwady', 'BGO', null);
INSERT INTO `cities` VALUES ('Thegon', 'BGO', null);
INSERT INTO `cities` VALUES ('Zigon', 'BGO', null);

INSERT INTO `cities` VALUES ('Falam', 'CHN', null);
INSERT INTO `cities` VALUES ('Hakha', 'CHN', null);
INSERT INTO `cities` VALUES ('Htantlang', 'CHN', null);
INSERT INTO `cities` VALUES ('Kanpetlet', 'CHN', null);
INSERT INTO `cities` VALUES ('Madupi', 'CHN', null);
INSERT INTO `cities` VALUES ('Mindat', 'CHN', null);
INSERT INTO `cities` VALUES ('Paletwa', 'CHN', null);
INSERT INTO `cities` VALUES ('Tiddim', 'CHN', null);
INSERT INTO `cities` VALUES ('Tonzang', 'CHN', null);

INSERT INTO `cities` VALUES ('Bhamo', 'KCH', null);
INSERT INTO `cities` VALUES ('Chipwi', 'KCH', null);
INSERT INTO `cities` VALUES ('Hpakan', 'KCH', null);
INSERT INTO `cities` VALUES ('Injangyang', 'KCH', null);
INSERT INTO `cities` VALUES ('Kawnglanghpu', 'KCH', null);
INSERT INTO `cities` VALUES ('Machanbaw', 'KCH', null);
INSERT INTO `cities` VALUES ('Mansi', 'KCH', null);
INSERT INTO `cities` VALUES ('Mogaung', 'KCH', null);
INSERT INTO `cities` VALUES ('Mohnyin', 'KCH', null);
INSERT INTO `cities` VALUES ('Momauk', 'KCH', null);
INSERT INTO `cities` VALUES ('Myitkyina', 'KCH', null);
INSERT INTO `cities` VALUES ('Nogmung', 'KCH', null);
INSERT INTO `cities` VALUES ('Puta-O', 'KCH', null);
INSERT INTO `cities` VALUES ('Shwegu', 'KCH', null);
INSERT INTO `cities` VALUES ('Sumprabum', 'KCH', null);
INSERT INTO `cities` VALUES ('Tanai', 'KCH', null);
INSERT INTO `cities` VALUES ('Tsawlaw', 'KCH', null);
INSERT INTO `cities` VALUES ('Waingmaw', 'KCH', null);

INSERT INTO `cities` VALUES ('Bawlakhe', 'KYH', null);
INSERT INTO `cities` VALUES ('Demoso', 'KYH', null);
INSERT INTO `cities` VALUES ('Hpasawng', 'KYH', null);
INSERT INTO `cities` VALUES ('Hpruso', 'KYH', null);
INSERT INTO `cities` VALUES ('Loikaw', 'KYH', null);
INSERT INTO `cities` VALUES ('Mese', 'KYH', null);
INSERT INTO `cities` VALUES ('Shadaw', 'KYH', null);

INSERT INTO `cities` VALUES ('Hlaingbwe', 'KYN', null);
INSERT INTO `cities` VALUES ('Hpa-An', 'KYN', null);
INSERT INTO `cities` VALUES ('Hpapun', 'KYN', null);
INSERT INTO `cities` VALUES ('Kawkareik', 'KYN', null);
INSERT INTO `cities` VALUES ('Kyain Seikgyi', 'KYN', null);
INSERT INTO `cities` VALUES ('Myawaddy', 'KYN', null);
INSERT INTO `cities` VALUES ('Thandaung', 'KYN', null);

INSERT INTO `cities` VALUES ('Aunglan', 'MGY', null);
INSERT INTO `cities` VALUES ('Chauk', 'MGY', null);
INSERT INTO `cities` VALUES ('Gangaw', 'MGY', null);
INSERT INTO `cities` VALUES ('Kamma', 'MGY', null);
INSERT INTO `cities` VALUES ('Magway', 'MGY', null);
INSERT INTO `cities` VALUES ('Minbu', 'MGY', null);
INSERT INTO `cities` VALUES ('Mindon', 'MGY', null);
INSERT INTO `cities` VALUES ('Minhla', 'MGY', null);
INSERT INTO `cities` VALUES ('Myaing', 'MGY', null);
INSERT INTO `cities` VALUES ('Myothit', 'MGY', null);
INSERT INTO `cities` VALUES ('Natmauk', 'MGY', null);
INSERT INTO `cities` VALUES ('Ngape', 'MGY', null);
INSERT INTO `cities` VALUES ('Pakokku', 'MGY', null);
INSERT INTO `cities` VALUES ('Pauk', 'MGY', null);
INSERT INTO `cities` VALUES ('Pwintbyu', 'MGY', null);
INSERT INTO `cities` VALUES ('Salin', 'MGY', null);
INSERT INTO `cities` VALUES ('Saw', 'MGY', null);
INSERT INTO `cities` VALUES ('Seikphyu', 'MGY', null);
INSERT INTO `cities` VALUES ('Sidoktaya', 'MGY', null);
INSERT INTO `cities` VALUES ('Sinbaungwe', 'MGY', null);
INSERT INTO `cities` VALUES ('Taungdwingyi', 'MGY', null);
INSERT INTO `cities` VALUES ('Thayet', 'MGY', null);
INSERT INTO `cities` VALUES ('Tilin', 'MGY', null);
INSERT INTO `cities` VALUES ('Yenangyaung', 'MGY', null);
INSERT INTO `cities` VALUES ('Yesagyo', 'MGY', null);

INSERT INTO `cities` VALUES ('Amarapura', 'MDY', null);
INSERT INTO `cities` VALUES ('Aungmyaythazan', 'MDY', null);
INSERT INTO `cities` VALUES ('Chanayethazan', 'MDY', null);
INSERT INTO `cities` VALUES ('Chanmyathazi', 'MDY', null);
INSERT INTO `cities` VALUES ('Kyaukpadaung', 'MDY', null);
INSERT INTO `cities` VALUES ('Kyaukse', 'MDY', null);
-- INSERT INTO `cities` VALUES ('Lewe', 'MDY', null);
INSERT INTO `cities` VALUES ('Madaya', 'MDY', null);
INSERT INTO `cities` VALUES ('Mahaaungmyay', 'MDY', null);
INSERT INTO `cities` VALUES ('Mahlaing', 'MDY', null);
INSERT INTO `cities` VALUES ('Meiktila', 'MDY', null);
INSERT INTO `cities` VALUES ('Mogoke', 'MDY', null);
INSERT INTO `cities` VALUES ('Myingyan', 'MDY', null);
INSERT INTO `cities` VALUES ('Myittha', 'MDY', null);
INSERT INTO `cities` VALUES ('Natogyi', 'MDY', null);
INSERT INTO `cities` VALUES ('Ngazun', 'MDY', null);
INSERT INTO `cities` VALUES ('Nyaung-U', 'MDY', null);
INSERT INTO `cities` VALUES ('Patheingyi', 'MDY', null);
INSERT INTO `cities` VALUES ('Pyawbwe', 'MDY', null);
INSERT INTO `cities` VALUES ('Pyigyitagon', 'MDY', null);
-- INSERT INTO `cities` VALUES ('Pyinmana', 'MDY', null);
INSERT INTO `cities` VALUES ('Pyinoolwin', 'MDY', null);
INSERT INTO `cities` VALUES ('Singu', 'MDY', null);
INSERT INTO `cities` VALUES ('Sintgaing', 'MDY', null);
INSERT INTO `cities` VALUES ('Tada-U', 'MDY', null);
INSERT INTO `cities` VALUES ('Tatkon', 'MDY', null);
INSERT INTO `cities` VALUES ('Taungtha', 'MDY', null);
INSERT INTO `cities` VALUES ('Thabeikkyin', 'MDY', null);
INSERT INTO `cities` VALUES ('Thazi', 'MDY', null);
INSERT INTO `cities` VALUES ('Wundwin', 'MDY', null);
INSERT INTO `cities` VALUES ('Yamethin', 'MDY', null);

INSERT INTO `cities` VALUES ('Bilin', 'MON', null);
INSERT INTO `cities` VALUES ('Chaungzon', 'MON', null);
INSERT INTO `cities` VALUES ('Kyaikmaraw', 'MON', null);
INSERT INTO `cities` VALUES ('Kyaikto', 'MON', null);
INSERT INTO `cities` VALUES ('Mawlamyine', 'MON', null);
INSERT INTO `cities` VALUES ('Mudon', 'MON', null);
INSERT INTO `cities` VALUES ('Paung', 'MON', null);
INSERT INTO `cities` VALUES ('Thanbyuzayat', 'MON', null);
INSERT INTO `cities` VALUES ('Thaton', 'MON', null);
INSERT INTO `cities` VALUES ('Ye', 'MON', null);

INSERT INTO `cities` VALUES ('Ann', 'RKH', null);
INSERT INTO `cities` VALUES ('Buthidaung', 'RKH', null);
INSERT INTO `cities` VALUES ('Gwa', 'RKH', null);
INSERT INTO `cities` VALUES ('Kyaukpyu', 'RKH', null);
INSERT INTO `cities` VALUES ('Kyauktaw', 'RKH', null);
INSERT INTO `cities` VALUES ('Maungdaw', 'RKH', null);
INSERT INTO `cities` VALUES ('Minbya', 'RKH', null);
INSERT INTO `cities` VALUES ('Mrauk-U', 'RKH', null);
INSERT INTO `cities` VALUES ('Munaung', 'RKH', null);
INSERT INTO `cities` VALUES ('Myebon', 'RKH', null);
INSERT INTO `cities` VALUES ('Pauktaw', 'RKH', null);
INSERT INTO `cities` VALUES ('Ponnagyun', 'RKH', null);
INSERT INTO `cities` VALUES ('Ramree', 'RKH', null);
INSERT INTO `cities` VALUES ('Rathedaung', 'RKH', null);
INSERT INTO `cities` VALUES ('Sittwe', 'RKH', null);
INSERT INTO `cities` VALUES ('Thandwe', 'RKH', null);
INSERT INTO `cities` VALUES ('Toungup', 'RKH', null);

INSERT INTO `cities` VALUES ('Ayadaw', 'SGG', null);
INSERT INTO `cities` VALUES ('Banmauk', 'SGG', null);
INSERT INTO `cities` VALUES ('Budalin', 'SGG', null);
INSERT INTO `cities` VALUES ('Chaung-U', 'SGG', null);
INSERT INTO `cities` VALUES ('Hkamti', 'SGG', null);
INSERT INTO `cities` VALUES ('Homalin', 'SGG', null);
INSERT INTO `cities` VALUES ('Indaw', 'SGG', null);
INSERT INTO `cities` VALUES ('Kale', 'SGG', null);
INSERT INTO `cities` VALUES ('Kalewa', 'SGG', null);
INSERT INTO `cities` VALUES ('Kanbalu', 'SGG', null);
INSERT INTO `cities` VALUES ('Kani', 'SGG', null);
INSERT INTO `cities` VALUES ('Katha', 'SGG', null);
INSERT INTO `cities` VALUES ('Kawlin', 'SGG', null);
INSERT INTO `cities` VALUES ('Khin-U', 'SGG', null);
INSERT INTO `cities` VALUES ('Kyunhla', 'SGG', null);
INSERT INTO `cities` VALUES ('Lahe', 'SGG', null);
INSERT INTO `cities` VALUES ('Lay Shi', 'SGG', null);
INSERT INTO `cities` VALUES ('Mawlaik', 'SGG', null);
INSERT INTO `cities` VALUES ('Mingin', 'SGG', null);
INSERT INTO `cities` VALUES ('Monywa', 'SGG', null);
INSERT INTO `cities` VALUES ('Myaung', 'SGG', null);
INSERT INTO `cities` VALUES ('Myinmu', 'SGG', null);
INSERT INTO `cities` VALUES ('Nanyun', 'SGG', null);
INSERT INTO `cities` VALUES ('Pale', 'SGG', null);
INSERT INTO `cities` VALUES ('Paungbyin', 'SGG', null);
INSERT INTO `cities` VALUES ('Pinlebu', 'SGG', null);
INSERT INTO `cities` VALUES ('Sagaing', 'SGG', null);
INSERT INTO `cities` VALUES ('Salingyi', 'SGG', null);
INSERT INTO `cities` VALUES ('Shwebo', 'SGG', null);
INSERT INTO `cities` VALUES ('Tabayin', 'SGG', null);
INSERT INTO `cities` VALUES ('Tamu', 'SGG', null);
INSERT INTO `cities` VALUES ('Taze', 'SGG', null);
INSERT INTO `cities` VALUES ('Tigyaing', 'SGG', null);
INSERT INTO `cities` VALUES ('Wetlet', 'SGG', null);
INSERT INTO `cities` VALUES ('Wuntho', 'SGG', null);
INSERT INTO `cities` VALUES ('Ye-U', 'SGG', null);
INSERT INTO `cities` VALUES ('Yinmabin', 'SGG', null);

INSERT INTO `cities` VALUES ('Kengtung', 'SHN', null);
INSERT INTO `cities` VALUES ('Matman', 'SHN', null);
INSERT INTO `cities` VALUES ('Monghpyak', 'SHN', null);
INSERT INTO `cities` VALUES ('Monghsat', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongkhet', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongla', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongping', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongton', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongyang', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongyawng', 'SHN', null);
INSERT INTO `cities` VALUES ('Tachileik', 'SHN', null);
INSERT INTO `cities` VALUES ('Hopang', 'SHN', null);
INSERT INTO `cities` VALUES ('Hseni', 'SHN', null);
INSERT INTO `cities` VALUES ('Hsipaw', 'SHN', null);
INSERT INTO `cities` VALUES ('Konkyan', 'SHN', null);
INSERT INTO `cities` VALUES ('Kunlong', 'SHN', null);
INSERT INTO `cities` VALUES ('Kutkai', 'SHN', null);
INSERT INTO `cities` VALUES ('Kyuakme', 'SHN', null);
INSERT INTO `cities` VALUES ('Lashio', 'SHN', null);
INSERT INTO `cities` VALUES ('Laukkaing', 'SHN', null);
INSERT INTO `cities` VALUES ('Mabein', 'SHN', null);
INSERT INTO `cities` VALUES ('Manton', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongmao', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongmit', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongyai', 'SHN', null);
INSERT INTO `cities` VALUES ('Muse', 'SHN', null);
INSERT INTO `cities` VALUES ('Namhsan', 'SHN', null);
INSERT INTO `cities` VALUES ('Namphan', 'SHN', null);
INSERT INTO `cities` VALUES ('Namtu', 'SHN', null);
INSERT INTO `cities` VALUES ('Nanhkan', 'SHN', null);
INSERT INTO `cities` VALUES ('Nawnghkio', 'SHN', null);
INSERT INTO `cities` VALUES ('Pangsang', 'SHN', null);
INSERT INTO `cities` VALUES ('Pangwaun', 'SHN', null);
INSERT INTO `cities` VALUES ('Tangyan', 'SHN', null);
INSERT INTO `cities` VALUES ('Hopong', 'SHN', null);
INSERT INTO `cities` VALUES ('Hsihseng', 'SHN', null);
INSERT INTO `cities` VALUES ('Kalaw', 'SHN', null);
INSERT INTO `cities` VALUES ('Kunhing', 'SHN', null);
INSERT INTO `cities` VALUES ('Kyethi', 'SHN', null);
INSERT INTO `cities` VALUES ('Laihka', 'SHN', null);
INSERT INTO `cities` VALUES ('Langkho', 'SHN', null);
INSERT INTO `cities` VALUES ('Lawksawk', 'SHN', null);
INSERT INTO `cities` VALUES ('Loilen', 'SHN', null);
INSERT INTO `cities` VALUES ('Mawkmai', 'SHN', null);
INSERT INTO `cities` VALUES ('Monghsu', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongkaung', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongnai', 'SHN', null);
INSERT INTO `cities` VALUES ('Mongpan', 'SHN', null);
INSERT INTO `cities` VALUES ('Nansang', 'SHN', null);
INSERT INTO `cities` VALUES ('Nyaungshwe', 'SHN', null);
INSERT INTO `cities` VALUES ('Pekon', 'SHN', null);
INSERT INTO `cities` VALUES ('Pindaya', 'SHN', null);
INSERT INTO `cities` VALUES ('Pinlaung', 'SHN', null);
INSERT INTO `cities` VALUES ('Taunggyi', 'SHN', null);
INSERT INTO `cities` VALUES ('Ywangan', 'SHN', null);


INSERT INTO `cities` VALUES ('Bokpyin', 'TNY', null);
INSERT INTO `cities` VALUES ('Dawei', 'TNY', null);
INSERT INTO `cities` VALUES ('Kawthoung', 'TNY', null);
INSERT INTO `cities` VALUES ('Kyunsu', 'TNY', null);
INSERT INTO `cities` VALUES ('Launglon', 'TNY', null);
INSERT INTO `cities` VALUES ('Myeik', 'TNY', null);
INSERT INTO `cities` VALUES ('Palaw', 'TNY', null);
INSERT INTO `cities` VALUES ('Tanintharyi', 'TNY', null);
INSERT INTO `cities` VALUES ('Thayetchaung', 'TNY', null);
INSERT INTO `cities` VALUES ('Yebyu', 'TNY', null);

INSERT INTO `cities` VALUES ('Ahlone', 'YGN', null);
INSERT INTO `cities` VALUES ('Bahan', 'YGN', null);
INSERT INTO `cities` VALUES ('Botahtaung', 'YGN', null);
INSERT INTO `cities` VALUES ('Cocokyun', 'YGN', null);
INSERT INTO `cities` VALUES ('Dagon', 'YGN', null);
INSERT INTO `cities` VALUES ('Dagon Myothit(East)', 'YGN', null);
INSERT INTO `cities` VALUES ('Dagon Myothit(North)', 'YGN', null);
INSERT INTO `cities` VALUES ('Dagon Myothit(Seikkan)', 'YGN', null);
INSERT INTO `cities` VALUES ('Dagon Myothit(South)', 'YGN', null);
INSERT INTO `cities` VALUES ('Dala', 'YGN', null);
INSERT INTO `cities` VALUES ('Dawbon', 'YGN', null);
INSERT INTO `cities` VALUES ('Hlaing', 'YGN', null);
INSERT INTO `cities` VALUES ('Hlaingtharya', 'YGN', null);
INSERT INTO `cities` VALUES ('Hlegu', 'YGN', null);
INSERT INTO `cities` VALUES ('Hmawbi', 'YGN', null);
INSERT INTO `cities` VALUES ('Htantabin', 'YGN', null);
INSERT INTO `cities` VALUES ('Insein', 'YGN', null);
INSERT INTO `cities` VALUES ('Kamaryut', 'YGN', null);
INSERT INTO `cities` VALUES ('Kawhmu', 'YGN', null);
INSERT INTO `cities` VALUES ('Kayan', 'YGN', null);
INSERT INTO `cities` VALUES ('Kungyangon', 'YGN', null);
INSERT INTO `cities` VALUES ('Kyauktada', 'YGN', null);
INSERT INTO `cities` VALUES ('Kyauktan', 'YGN', null);
INSERT INTO `cities` VALUES ('Kyeemyindaing', 'YGN', null);
INSERT INTO `cities` VALUES ('Lanmadaw', 'YGN', null);
INSERT INTO `cities` VALUES ('Latha', 'YGN', null);
INSERT INTO `cities` VALUES ('Mayangone', 'YGN', null);
INSERT INTO `cities` VALUES ('Mingaladon', 'YGN', null);
INSERT INTO `cities` VALUES ('Mingalartaungnyunt', 'YGN', null);
INSERT INTO `cities` VALUES ('North Okkalapa', 'YGN', null);
INSERT INTO `cities` VALUES ('Pabedan', 'YGN', null);
INSERT INTO `cities` VALUES ('Pazundaung', 'YGN', null);
INSERT INTO `cities` VALUES ('Sanchaung', 'YGN', null);
INSERT INTO `cities` VALUES ('Seikgyikanaungto', 'YGN', null);
INSERT INTO `cities` VALUES ('Seikkan', 'YGN', null);
INSERT INTO `cities` VALUES ('Shwepyithar', 'YGN', null);
INSERT INTO `cities` VALUES ('South Okkalapa', 'YGN', null);
INSERT INTO `cities` VALUES ('Taikkyi', 'YGN', null);
INSERT INTO `cities` VALUES ('Tamwe', 'YGN', null);
INSERT INTO `cities` VALUES ('Thaketa', 'YGN', null);
INSERT INTO `cities` VALUES ('Thanlyin', 'YGN', null);
INSERT INTO `cities` VALUES ('Thingangkuun', 'YGN', null);
INSERT INTO `cities` VALUES ('Thongwa', 'YGN', null);
INSERT INTO `cities` VALUES ('Twantay', 'YGN', null);
INSERT INTO `cities` VALUES ('Yankin', 'YGN', null);

INSERT INTO `cities` VALUES ('Ottarathiri', 'NPT', null);
INSERT INTO `cities` VALUES ('Pobbathiri', 'NPT', null);
INSERT INTO `cities` VALUES ('Tatkone', 'NPT', null);
INSERT INTO `cities` VALUES ('Zeyathiri', 'NPT', null);
INSERT INTO `cities` VALUES ('Dekkhinathiri', 'NPT', null);
INSERT INTO `cities` VALUES ('Lewe', 'NPT', null);
INSERT INTO `cities` VALUES ('Pyinmana', 'NPT', null);
INSERT INTO `cities` VALUES ('Zabuthiri', 'NPT', null);
        ");
        DB::commit();
    }
}